from pydantic import BaseModel, Field
from typing import List
from datetime import datetime

class AnalysisResponse(BaseModel):
    """
    Schema for the analysis result sent to the client.
    """
    match_score: float = Field(..., description="The calculated match score between 0 and 100.")
    missing_skills: List[str] = Field(..., description="A list of critical skills missing from the resume.")
    resume_suggestions: List[str] = Field(..., description="Actionable suggestions to improve the resume.")
    generated_cover_letter: str = Field(..., description="A tailored cover letter generated by the AI.")

class AnalysisHistoryItem(AnalysisResponse):
    """
    Schema for representing a single analysis result from the database history.
    """
    id: str
    analyzed_at: datetime